/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Lock__factory } from "./Lock__factory";
export { Web3Button__factory } from "./Web3Button__factory";
